// <auto-generated />
using System;
using AquaTrack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaTrack.Migrations
{
    [DbContext(typeof(BancoDeDados))]
    partial class BancoDeDadosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaTrack.Models.Leitura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Apartamento")
                        .HasColumnType("integer");

                    b.Property<string>("Bloco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Consumo")
                        .HasColumnType("integer");

                   //ab.Property<DateTime>("DataLeitura")
                       //.HasColumnType("timestamp with time zone");

                    b.Property<int>("LeituraAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("LeituraAtual")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
